client_config_backend: settings
client_config:
  client_id: 541565548983-eqk1sgvjpdt3m5qa8lpcekdh5qq9rls7.apps.googleusercontent.com
  client_secret: SxHxbFIMYoX4jKM1UBCbgUo-

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install



